[package]
name = "train_example"
type = "contract"
authors = [""]
compiler_version = "1.0.0"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/aztec-nr/aztec" }
# token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v1.2.1", directory="noir-projects/noir-contracts/contracts/app/token_contract" }
token_contract = { git="https://github.com/defi-wonderland/aztec-standards/", tag="v1.2.1", directory="src/token_contract" }
# token = { path = "../../../../aztec-standards/src/token_contract" }
sha256 = { tag = "v0.1.2", git = "https://github.com/noir-lang/sha256" }